# Generated by Django 3.0.3 on 2020-04-24 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applvl3', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
