# Generated by Django 3.0.3 on 2020-04-23 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0002_auto_20200423_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='useremail',
            new_name='email',
        ),
    ]
